# Generated by Django 6.1 on 2026-09-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamingcenter',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamingcenter',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
