# Generated by Django 6.1 on 2026-09-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_gamingcenter_latitude_gamingcenter_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamingcenter',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
