# Generated by Django 6.1 on 2026-09-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_gamingcenter_google_maps_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamingcenter',
            name='google_maps_url',
        ),
    ]
