# Generated by Django 6.1 on 2026-09-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_remove_gamingcenter_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamingcenter',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
