# Generated by Django 6.1 on 2026-09-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_is_paid_booking_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='lock_token',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
