# Generated by Django 6.1 on 2026-09-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_lock_token_booking_locked_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='lock_token',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='locked_until',
        ),
        migrations.AddField(
            model_name='slot',
            name='lock_token',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
